-- MySQL Script generated by MySQL Workbench
-- Tue May 22 13:59:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema VeselovMessenger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema VeselovMessenger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `VeselovMessenger` DEFAULT CHARACTER SET utf8 ;
USE `VeselovMessenger` ;

-- -----------------------------------------------------
-- Table `VeselovMessenger`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeselovMessenger`.`User` (
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VeselovMessenger`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VeselovMessenger`.`Messages` (
  `sender` VARCHAR(40) NOT NULL,
  `addressee` VARCHAR(40) NOT NULL,
  `date` DATETIME NOT NULL,
  `text` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`sender`, `addressee`, `date`, `text`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
